runtime: aspnetcore
env: flex

# Cấu hình tài nguyên
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Cấu hình mở rộng
manual_scaling:
  instances: 1
  
# Hoặc sử dụng auto scaling
# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 5
#   cool_down_period_sec: 60
#   cpu_utilization:
#     target_utilization: 0.6

# Cấu hình môi trường
env_variables:
  ASPNETCORE_ENVIRONMENT: "Production"